# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  活到老学到老
subtitle: 分享技术，技术总结
name: 小明的博客
email: 965537330@qq.com
description: 本站是小明同学的技术分享博客。内容目前涵盖Java后端技术相关的研究与知识分享。
keywords: Spring,Spring Boot,Spring Cloud,Jvm,开发者,编程,代码,IT技术博客,Java,Python,
encoding: "utf-8"
favicon: favicon.ico 

repository: WangYMcc/wangymcc.github.io
github_url: https://github.com/blog
url: https://WangYMcc.github.io
enforce_ssl: 

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:
  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self

  -
    href: /about.html
    label: 关于
    target: _self

# Navigation. main menu list
navs:
  -
    href: /
    label: Home


  -
    href: /spring-boot.html
    label: Spring Boot
    target: _self
    subnav:

      -
        subHref: /spring-boot.html
        subLabel: Spring Boot

      -
        subHref: /spring-cloud.html
        subLabel: Spring Cloud

  -
    href: http://www.justdojava.com
    label: Java
    target: _blank
    subnav:

      -
        subHref: /java.html
        subLabel: Jvm 系列文章
        
      -
        subHref: http://www.justdojava.com
        subLabel: Java 极客技术
        target: _blank

#  -
#
#    href: /python.html
#    label: Python
#    subnav:
#
#      -
#        subHref: /python.html
#        subLabel: Python 教程
#
#      -
#        subHref: http://www.justdopython.com
#        subLabel: Python 技术
#        target: _blank



# labels. my blog key words
labels:
#  -
#    href: http://favorites.ren/stock.html
#    label: 股票
#    target: _blank


# selected articles
classes:
  -
    href: /life.html
    name: 我的故事
    describe: 分享一些我的故事




# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: WangYMcc
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: WangYMcc
#    repo: blog-comments
#    oauth:
#        client_id: ff99557e4cce1400187e
#        client_secret: d6e050dc5ed22efa4f7ff04cd0c2a9cbb63e9e57
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: WangYMcc
    repo: blog-comments
    clientID: 3d9210b2bdd1458b2a69
    clientSecret: 2023b0407d142ed1a270b7353030c42a0bec4fea
# 在使用其它评论组件时可点击显示 Disqus
#lazy_load_disqus : false
